#!/bin/sh

set -e

case "$1" in
    configure)
	# continue below
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
    ;;
esac

#DEBHELPER#

# Alternatives packaged as ksh and mksh
update-alternatives --install /bin/ksh ksh /bin/ksh93 20 \
                    --slave /usr/share/man/man1/ksh.1.gz ksh.1.gz \
                            /usr/share/man/man1/ksh93.1.gz \
		    --slave /usr/share/binfmts/ksh ksh-binfmt \
			    /usr/share/ksh/ksh93.binfmt \
                    --slave /bin/rksh rksh /bin/rksh93 \
                    --slave /usr/share/man/man1/rksh.1.gz rksh.1.gz \
                            /usr/share/man/man1/rksh93.1.gz

update-alternatives --install /usr/bin/shcomp shcomp /usr/bin/shcomp93 20 \
                    --slave /usr/share/man/man1/shcomp.1.gz shcomp.1.gz \
                            /usr/share/man/man1/shcomp93.1.gz

if command -v update-binfmts >/dev/null && test -r /usr/share/binfmts/ksh; then
	# ignore error, it probably was registered by ksh
	update-binfmts --package ksh93u+m --import ksh || true
fi

# create compatibility symlink if necessary
test -e /usr/bin/ksh || test -h /usr/bin/ksh || \
    ln -s /bin/ksh /usr/bin/ksh

add-shell /bin/ksh93
add-shell /bin/rksh93

exit 0
